// JavaScript Document
(function newText() {
  let texts = ['Chase Your Dreams. Then The Bag.', 'Choose Life, You Never Know When Your Time Is Next.' , 'Repeat After Me: I Am The Goat. F@ck The Rest.', 'Take Your Time, Swag Is Not Built In A Day.', 'Do Not Listen To People. Just Focus On What Is Truly Right.', 'I Love You...Now Go & Tell Your Family & Friends The Same Thing.', 'Overthinking Can Lead To Your Ultimate Demise. Start Doing.', 'Stop Stressing About The Little Things When There Is So Much To Live For. Smoke A Blunt Or Breathe.', 'Please Do Not Smoke Crack. Make It Then Sell It. *metaphorically speaking*', 'Would You Rather Live Comfortably With No Money Or Chaotically Unhappy With All The Money?', 'Those Intrusive Thoughts In Your Head Are Up To No Good.', 'Educate Yourself. Seriously, Its Too Common To Be Stupid Nowadays.', 'Politics...Thats It. Thats The Joke.', 'Stick To What Is Real Or Get Lost & Forgotten With The Fakes. Your Choice.', 'A Marketplace For Dope Fiends & Dope A$$ Fiends.', 'Make Smack DVD Great Again. And Bring Back Freaknik.', 'Controversy Matters More Than The Shock Value It Creates.', 'While You Look, Think About Just How Nice YOU Would Look. :)', 'Hi.', 'Just In Case, Always Have A Contingency For The Bull$hit.', 'This Was Not That Hard To Do. Try It Out.', 'Ask Yourself The Right Questions Before Getting Hung Up On The Wrong Answers.', 'Love Yourz. Like Jermaine Said.', 'Preach It To The Choir, But God May Not Stand For it.', 'Try & Indulge In Everything That This World Has To Offer. You Might Like Something.', 'People Will Not Find Something Harmful Until It Happens To Someone They Care About.', 'Honor Your Life & Loved Ones Like You Honor Your Idols.', 'Why Are You Being Hard On Yourself? No One Knows How Life Works.', 'Stop Trying To Impress People Who Do Not Care About You.', '"528HZ Is Found To Be The Frequency Of A Stars Center, Or Heartbeat." - Some Rando', 'I Turn My Face Away & Lose Half Of The World.', 'Stay True To Your Drip. & Your Business.', 'STOP WAITING TO CREATE THE LIFE YOU TRULY WANT.', 'Rip The Band-aid Off & Stop Waiting. No One Else Is Gonna Do It For You.', 'THIS IS A FILM ABOUT YOU.', 'To Each Their Own. Its Too Easy To Hate, Just Respect It.', 'Sometimes, You Need Flex To Yourself To Feel Better.'];
  let randomText = Math.floor(Math.random() * texts.length);
  document.getElementById('textDisplay').innerHTML = texts[randomText];
})();

//fetch product title, price and descriptions
fetch('https://my-api/products/1')
	.then(response => response.json())
	.then(product => {
		document.querySelector('.product-title').innerText = product.title;
		document.querySelector('.product-description').innerText = product.description;
		document.querySelector('.product-price').innerText = product.price;
})